# Generated by Django 3.0.6 on 2020-05-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpiekunSali',
            fields=[
                ('id_opiekuna', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=64)),
                ('nazwisko', models.CharField(max_length=64)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('numer_telefonu', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'opiekun_sali',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id_rezerwacji', models.AutoField(primary_key=True, serialize=False)),
                ('data_zgloszenia', models.DateTimeField()),
                ('czy_anulowana', models.BooleanField()),
            ],
            options={
                'db_table': 'rezerwacja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RezerwacjaStanowiska',
            fields=[
                ('id_rezerwacji_stanowiska', models.AutoField(primary_key=True, serialize=False)),
                ('termin_rozpoczecia', models.DateTimeField()),
                ('termin_zakonczenia', models.DateTimeField()),
                ('czy_anulowana', models.BooleanField()),
                ('id_rezerwacji', models.ForeignKey(db_column='id_rezerwacji', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Rezerwacja')),
            ],
            options={
                'db_table': 'rezerwacja_stanowiska',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RodzajSali',
            fields=[
                ('id_rodzaju_sali', models.AutoField(primary_key=True, serialize=False)),
                ('rodzaj', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'rodzaj_sali',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rola',
            fields=[
                ('id_roli', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_roli', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'rola',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sali', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_sali', models.CharField(max_length=128)),
                ('budynek', models.CharField(blank=True, max_length=64, null=True)),
                ('opis_sali', models.TextField(blank=True, null=True)),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_opiekuna', models.ForeignKey(blank=True, db_column='id_opiekuna', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.OpiekunSali')),
                ('id_rodzaju_sali', models.ForeignKey(db_column='id_rodzaju_sali', on_delete=django.db.models.deletion.DO_NOTHING, to='app.RodzajSali')),
            ],
            options={
                'db_table': 'sala',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id_stanowiska', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_stanowiska', models.CharField(max_length=128)),
                ('opis_stanowiska', models.TextField(blank=True, null=True)),
                ('stopien_zaawansowania', models.IntegerField()),
                ('czy_dostepne', models.BooleanField()),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_sali', models.ForeignKey(db_column='id_sali', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Sala')),
            ],
            options={
                'db_table': 'stanowisko',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id_uzytkownika', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(blank=True, max_length=64, null=True)),
                ('nazwisko', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(max_length=128)),
                ('haslo', models.CharField(max_length=128)),
                ('id_roli', models.ForeignKey(db_column='id_roli', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Rola')),
            ],
            options={
                'db_table': 'uzytkownik',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.AddField(
            model_name='rezerwacjastanowiska',
            name='id_stanowiska',
            field=models.ForeignKey(db_column='id_stanowiska', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Stanowisko'),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='id_uzytkownika',
            field=models.ForeignKey(db_column='id_uzytkownika', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Uzytkownik'),
        ),
    ]
