# Generated by Django 3.0.6 on 2020-05-18 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200514_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login'),
        ),
    ]
