# Generated by Django 3.0.6 on 2020-05-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uzytkownik_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzytkownik',
            name='last_login',
        ),
    ]
