# Generated by Django 3.0.6 on 2020-05-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_uzytkownik_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
