# Generated by Django 3.0.6 on 2020-05-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uzytkownik_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='is_superuser',
            field=models.IntegerField(default=False),
        ),
    ]
