# Generated by Django 3.0.6 on 2020-05-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200525_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.AlterModelOptions(
            name='rezerwacja',
            options={'managed': True, 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='rezerwacja',
            name='data_zgloszenia',
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='event_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
