# Generated by Django 3.0.6 on 2020-06-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200527_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opiekunsali',
            options={'managed': True, 'verbose_name_plural': 'Opiekunowie Sali'},
        ),
        migrations.AlterModelOptions(
            name='rezerwacja',
            options={'managed': True, 'verbose_name': 'Rezerwacja', 'verbose_name_plural': 'Rezerwacje'},
        ),
        migrations.AlterModelOptions(
            name='rezerwacjastanowiska',
            options={'managed': True, 'verbose_name_plural': 'Rezerwacje Stanowiska'},
        ),
        migrations.AlterModelOptions(
            name='rodzajsali',
            options={'managed': True, 'verbose_name_plural': 'Rodzaje Sali'},
        ),
        migrations.AlterModelOptions(
            name='rola',
            options={'managed': True, 'verbose_name_plural': 'Role'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'managed': True, 'verbose_name_plural': 'Sale'},
        ),
        migrations.AlterModelOptions(
            name='stanowisko',
            options={'managed': True, 'verbose_name_plural': 'Stanowiska'},
        ),
        migrations.AlterModelOptions(
            name='uzytkownik',
            options={'managed': True, 'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AddField(
            model_name='sala',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
