# Generated by Django 3.0.6 on 2020-06-02 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200601_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='zdjecie',
        ),
    ]
