# Generated by Django 3.0.6 on 2020-06-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200603_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaOpiekun',
            fields=[
                ('id_sala_opiekun', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'SalaOpiekun',
                'db_table': 'sala_opiekun',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='sala',
            name='id_opiekuna',
        ),
    ]
