# Generated by Django 3.0.6 on 2020-06-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200603_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opiekunsali',
            options={'managed': False, 'verbose_name_plural': 'Opiekunowie Sali'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'managed': False, 'verbose_name_plural': 'Sale'},
        ),
    ]
