# Generated by Django 3.0.6 on 2020-06-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200603_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opiekunsali',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rezerwacja',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rezerwacjastanowiska',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rodzajsali',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rola',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='salaopiekun',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stanowisko',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uzytkownik',
            options={'managed': False},
        ),
    ]
