# Generated by Django 3.0.6 on 2020-06-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200603_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opiekunsali',
            options={'managed': False, 'verbose_name_plural': 'Opiekunowie Sali'},
        ),
        migrations.AlterModelOptions(
            name='rezerwacja',
            options={'managed': True, 'verbose_name': 'Rezerwacja', 'verbose_name_plural': 'Rezerwacje'},
        ),
        migrations.AlterModelOptions(
            name='rezerwacjastanowiska',
            options={'managed': True, 'verbose_name_plural': 'Rezerwacje Stanowiska'},
        ),
        migrations.AlterModelOptions(
            name='rodzajsali',
            options={'managed': True, 'verbose_name_plural': 'Rodzaje Sali'},
        ),
        migrations.AlterModelOptions(
            name='rola',
            options={'managed': True, 'verbose_name_plural': 'Role'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'managed': False, 'verbose_name_plural': 'Sale'},
        ),
        migrations.AlterModelOptions(
            name='salaopiekun',
            options={'managed': False, 'verbose_name_plural': 'SalaOpiekun'},
        ),
        migrations.AlterModelOptions(
            name='stanowisko',
            options={'managed': True, 'verbose_name_plural': 'Stanowiska'},
        ),
        migrations.AlterModelOptions(
            name='uzytkownik',
            options={'managed': True, 'verbose_name_plural': 'Użytkownicy'},
        ),
    ]
