# Generated by Django 3.0.6 on 2020-06-12 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200603_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanowisko',
            name='id_sali',
            field=models.ForeignKey(db_column='id_sali', on_delete=django.db.models.deletion.CASCADE, to='app.Sala'),
        ),
        migrations.AlterField(
            model_name='stanowisko',
            name='stopien_zaawansowania',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Stopień zaawansowania (1-10)'),
        ),
    ]
